export const GET_PRODUCTS_REQUEST='GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR='GET_PRODUCTS_ERROR';

export const ADD_PRODUCTS_REQUEST='ADD_PRODUCTS_REQUEST';
export const ADD_PRODUCTS_SUCCESS='ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_ERROR='ADD_PRODUCTS_ERROR';

export const EDIT_PRODUCTS_REQUEST='EDIT_PRODUCTS_REQUEST';
export const EDIT_PRODUCTS_SUCCESS='EDIT_PRODUCTS_SUCCESS';
export const EDIT_PRODUCTS_ERROR='EDIT_PRODUCTS_ERROR';

export const DELETE_PRODUCTS_REQUEST='DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCTS_SUCCESS='DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_ERROR='DELETE_PRODUCTS_ERROR';